# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSfuc6XDe9jaooxGeomIgukqMiVoBsoj
"""

import pandas as pd
data = pd.read_csv("hotel_bookings.csv")
#print(data)
print(data.shape)

import pandas as pd
data = pd.read_csv("hotel_bookings.csv")
print(data.isnull().any().any())

import pandas as pd
data = pd.read_csv("hotel_bookings.csv")
isnullvalues = data.isnull().any().any()
print(data.isnull().sum())

import numpy as np
Missingvalues_agent = data['agent'].mean()
data["agent"].replace(np.NaN, Missingvalues_agent, inplace = True)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt

plt.boxplot(data["lead_time"])